'use strict';

const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');

const bcrypt = require('bcryptjs');

const { ask, askSecret, close } = require('./prompt');

const root = path.resolve(__dirname, '..');
const envPath = path.join(root, '.env');
const MIN_LENGTH = 12;

function buildEnv({ username, hash, secret, port, siteUrl, isProduction }) {
  return `# Generated by \`npm run setup\` on ${new Date().toISOString()}
# This file holds secrets. It is git-ignored: never commit it.

NODE_ENV=${isProduction ? 'production' : 'development'}
PORT=${port}
SITE_URL=${siteUrl}

ADMIN_USERNAME=${username}
ADMIN_PASSWORD_HASH=${hash}

SESSION_SECRET=${secret}
COOKIE_SECURE=${isProduction}

DATA_DIR=./data
UPLOAD_DIR=./uploads

MAX_IMAGE_BYTES=5242880
MAX_DOC_BYTES=10485760

TRUSTED_ORIGINS=
`;
}

async function main() {
  console.log('\nPortfolio setup\n----------------');

  if (fs.existsSync(envPath)) {
    const answer = await ask('.env already exists. Overwrite it? (y/N): ');
    if (answer.toLowerCase() !== 'y') {
      console.log('Cancelled. Nothing was changed.');
      return;
    }
  }

  const username = (await ask('Admin username: ')) || '';
  if (username.length < 3) {
    console.error('Username must be at least 3 characters.');
    process.exit(1);
  }

  const password = await askSecret(`Admin password (min ${MIN_LENGTH} chars): `);
  if (password.length < MIN_LENGTH) {
    console.error(`Password too short (${password.length}). Use at least ${MIN_LENGTH} characters.`);
    process.exit(1);
  }
  const confirm = await askSecret('Confirm password: ');
  if (password !== confirm) {
    console.error('Passwords do not match.');
    process.exit(1);
  }

  const portAnswer = (await ask('Port [3000]: ')) || '3000';
  const port = /^\d{2,5}$/.test(portAnswer) ? portAnswer : '3000';
  if (port !== portAnswer) {
    console.log(`  (ignoring "${portAnswer}", not a port number — using ${port})`);
  }

  const fallbackUrl = `http://localhost:${port}`;
  const urlAnswer = (await ask(`Site URL [${fallbackUrl}]: `)) || fallbackUrl;
  const siteUrl = /^https?:\/\/[^\s]+$/i.test(urlAnswer) ? urlAnswer.replace(/\/$/, '') : fallbackUrl;
  if (siteUrl !== urlAnswer.replace(/\/$/, '')) {
    console.log(`  (ignoring "${urlAnswer}", not an http(s) URL — using ${siteUrl})`);
  }

  const isProduction = siteUrl.startsWith('https://');

  const hash = await bcrypt.hash(password, 12);
  const secret = crypto.randomBytes(48).toString('base64url');

  fs.writeFileSync(envPath, buildEnv({ username, hash, secret, port, siteUrl, isProduction }), {
    encoding: 'utf8',
    mode: 0o600,
  });

  console.log('\nDone. .env created with:');
  console.log(`  - admin username: ${username}`);
  console.log('  - bcrypt password hash (the password itself was not saved)');
  console.log('  - a fresh random SESSION_SECRET');
  console.log(`  - port ${port} and site URL ${siteUrl}`);
  console.log('\nNext: npm start  then open the site and go to /admin\n');
}

main()
  .catch((error) => {
    console.error(error.message);
    process.exitCode = 1;
  })
  .finally(close);
